#!/usr/bin/env bash
set -euo pipefail

REPO_PATH=${REPO_PATH:-""}
MAX_ITERATIONS=${MAX_ITERATIONS:-5}
GITHUB_TOKEN=${GITHUB_TOKEN:-""}
GITHUB_REPO=${GITHUB_REPO:-""}
BASE_BRANCH=${BASE_BRANCH:-"main"}
AUTO_MERGE=${AUTO_MERGE:-"1"}

log() { printf "%s\n" "$*"; }

if [[ -z "$REPO_PATH" || -z "$GITHUB_TOKEN" || -z "$GITHUB_REPO" ]]; then
  log "Missing REPO_PATH/GITHUB_TOKEN/GITHUB_REPO"
  exit 2
fi

if ! command -v git >/dev/null 2>&1; then
  log "git not found"
  exit 2
fi

if ! command -v gh >/dev/null 2>&1; then
  log "gh CLI not found (install GitHub CLI)"
  exit 2
fi

if ! command -v codex >/dev/null 2>&1; then
  log "Installing codex CLI..."
  npm install -g @openai/codex
fi

git -C "$REPO_PATH" fetch origin "$BASE_BRANCH" >/dev/null 2>&1 || true

git -C "$REPO_PATH" diff --quiet || {
  log "Repo has uncommitted changes; aborting."
  exit 2
}

git -C "$REPO_PATH" checkout "$BASE_BRANCH" >/dev/null 2>&1

gh auth status -t >/dev/null 2>&1 || gh auth login --with-token <<<"$GITHUB_TOKEN" >/dev/null 2>&1 || true

for i in $(seq 1 "$MAX_ITERATIONS"); do
  ts=$(date +%Y%m%d%H%M%S)
  branch="auto-improve-${ts}-${i}"
  log "[${i}/${MAX_ITERATIONS}] Creating branch ${branch}"
  git -C "$REPO_PATH" checkout -b "$branch" >/dev/null 2>&1

  prompt="Improve the Electron app (UI/UX/robustness). Return a unified diff ONLY. No explanations."
  diff_file=$(mktemp)
  if ! codex exec --skip-git-repo-check "$prompt" >"$diff_file"; then
    log "Codex exec failed"
    git -C "$REPO_PATH" checkout "$BASE_BRANCH" >/dev/null 2>&1
    git -C "$REPO_PATH" branch -D "$branch" >/dev/null 2>&1 || true
    exit 2
  fi

  if [[ ! -s "$diff_file" ]]; then
    log "No diff returned. Stopping."
    git -C "$REPO_PATH" checkout "$BASE_BRANCH" >/dev/null 2>&1
    git -C "$REPO_PATH" branch -D "$branch" >/dev/null 2>&1 || true
    exit 0
  fi

  if ! git -C "$REPO_PATH" apply "$diff_file"; then
    log "Failed to apply diff. Stopping."
    git -C "$REPO_PATH" checkout "$BASE_BRANCH" >/dev/null 2>&1
    git -C "$REPO_PATH" branch -D "$branch" >/dev/null 2>&1 || true
    exit 2
  fi

  git -C "$REPO_PATH" add -A
  if git -C "$REPO_PATH" diff --cached --quiet; then
    log "No changes after apply. Stopping."
    git -C "$REPO_PATH" checkout "$BASE_BRANCH" >/dev/null 2>&1
    git -C "$REPO_PATH" branch -D "$branch" >/dev/null 2>&1 || true
    exit 0
  fi

  git -C "$REPO_PATH" commit -m "auto-improve: iteration ${i}" >/dev/null 2>&1
  git -C "$REPO_PATH" push origin HEAD >/dev/null 2>&1

  pr_title="Auto-improve iteration ${i}"
  pr_body="Automated improvement generated by Codex CLI."

  pr_url=$(gh pr create --repo "$GITHUB_REPO" --base "$BASE_BRANCH" --head "$branch" --title "$pr_title" --body "$pr_body")
  log "Created PR: $pr_url"

  if [[ "$AUTO_MERGE" == "1" ]]; then
    gh pr merge --auto --squash --repo "$GITHUB_REPO" "$pr_url" >/dev/null 2>&1 || log "Auto-merge not enabled."
  fi

  git -C "$REPO_PATH" checkout "$BASE_BRANCH" >/dev/null 2>&1

done

log "Done."
