const { app, BrowserWindow, ipcMain } = require("electron");
const path = require("path");
const pty = require("node-pty");
const { spawn } = require("child_process");
const { autoUpdater } = require("electron-updater");
const fs = require("fs");
const { existsSync } = require("fs");

let mainWindow = null;
let ptyProcess = null;

const IMPROVE_SCRIPT_CONTENT = `#!/usr/bin/env bash
set -euo pipefail

REPO_PATH=\${REPO_PATH:-""}
MAX_ITERATIONS=\${MAX_ITERATIONS:-5}
GITHUB_TOKEN=\${GITHUB_TOKEN:-""}
GITHUB_REPO=\${GITHUB_REPO:-""}
BASE_BRANCH=\${BASE_BRANCH:-"main"}
AUTO_MERGE=\${AUTO_MERGE:-"1"}

log() { printf "%s\\n" "$*"; }

if [[ -z "$REPO_PATH" ]]; then
  if [[ -d "/mnt/c/codex-ai-exe" ]]; then
    REPO_PATH="/mnt/c/codex-ai-exe"
  fi
fi

if [[ -z "$GITHUB_REPO" ]]; then
  GITHUB_REPO="mordechimenaker-create/codex-ai-exe"
fi

if [[ -z "$REPO_PATH" || -z "$GITHUB_TOKEN" || -z "$GITHUB_REPO" ]]; then
  log "Missing REPO_PATH/GITHUB_TOKEN/GITHUB_REPO"
  exit 2
fi

if ! command -v git >/dev/null 2>&1; then
  log "git not found"
  exit 2
fi

if ! command -v gh >/dev/null 2>&1; then
  log "gh CLI not found (install GitHub CLI)"
  exit 2
fi

if ! command -v codex >/dev/null 2>&1; then
  log "Installing codex CLI..."
  npm install -g @openai/codex
fi

git -C "$REPO_PATH" fetch origin "$BASE_BRANCH" >/dev/null 2>&1 || true

git -C "$REPO_PATH" diff --quiet || {
  log "Repo has uncommitted changes; aborting."
  exit 2
}

git -C "$REPO_PATH" checkout "$BASE_BRANCH" >/dev/null 2>&1

gh auth status -t >/dev/null 2>&1 || gh auth login --with-token <<<"$GITHUB_TOKEN" >/dev/null 2>&1 || true

for i in $(seq 1 "$MAX_ITERATIONS"); do
  ts=$(date +%Y%m%d%H%M%S)
  branch="auto-improve-\${ts}-\${i}"
  log "[\${i}/\${MAX_ITERATIONS}] Creating branch \${branch}"
  git -C "$REPO_PATH" checkout -b "$branch" >/dev/null 2>&1

  prompt="Improve the Electron app (UI/UX/robustness). Return a unified diff ONLY. No explanations."
  diff_file=$(mktemp)
  if ! codex exec --skip-git-repo-check "$prompt" >"$diff_file"; then
    log "Codex exec failed"
    git -C "$REPO_PATH" checkout "$BASE_BRANCH" >/dev/null 2>&1
    git -C "$REPO_PATH" branch -D "$branch" >/dev/null 2>&1 || true
    exit 2
  fi

  if [[ ! -s "$diff_file" ]]; then
    log "No diff returned. Stopping."
    git -C "$REPO_PATH" checkout "$BASE_BRANCH" >/dev/null 2>&1
    git -C "$REPO_PATH" branch -D "$branch" >/dev/null 2>&1 || true
    exit 0
  fi

  if ! git -C "$REPO_PATH" apply "$diff_file"; then
    log "Failed to apply diff. Stopping."
    git -C "$REPO_PATH" checkout "$BASE_BRANCH" >/dev/null 2>&1
    git -C "$REPO_PATH" branch -D "$branch" >/dev/null 2>&1 || true
    exit 2
  fi

  git -C "$REPO_PATH" add -A
  if git -C "$REPO_PATH" diff --cached --quiet; then
    log "No changes after apply. Stopping."
    git -C "$REPO_PATH" checkout "$BASE_BRANCH" >/dev/null 2>&1
    git -C "$REPO_PATH" branch -D "$branch" >/dev/null 2>&1 || true
    exit 0
  fi

  git -C "$REPO_PATH" commit -m "auto-improve: iteration \${i}" >/dev/null 2>&1
  git -C "$REPO_PATH" push "https://$GITHUB_TOKEN@github.com/$GITHUB_REPO.git" HEAD >/dev/null 2>&1

  pr_title="Auto-improve iteration \${i}"
  pr_body="Automated improvement generated by Codex CLI."

  pr_url=$(gh pr create --repo "$GITHUB_REPO" --base "$BASE_BRANCH" --head "$branch" --title "$pr_title" --body "$pr_body")
  log "Created PR: $pr_url"

  if [[ "$AUTO_MERGE" == "1" ]]; then
    gh pr merge --auto --squash --repo "$GITHUB_REPO" "$pr_url" >/dev/null 2>&1 || log "Auto-merge not enabled."
  fi

  git -C "$REPO_PATH" checkout "$BASE_BRANCH" >/dev/null 2>&1
done

log "Done."
`;

// Optional workarounds for environments with HTTPS interception or GPU issues.
if (process.env.ALLOW_INSECURE_CERTS === "1") {
  app.commandLine.appendSwitch("ignore-certificate-errors");
}
if (process.env.DISABLE_GPU === "1") {
  app.disableHardwareAcceleration();
  app.commandLine.appendSwitch("disable-gpu");
}

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1200,
    height: 800,
    backgroundColor: "#111113",
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
      contextIsolation: true,
      nodeIntegration: false
    }
  });

  mainWindow.loadFile(path.join(__dirname, "index.html"));

  mainWindow.on("closed", () => {
    mainWindow = null;
  });
}

function startPty() {
  if (process.platform !== "win32") {
    return;
  }

  const wslDistro = process.env.WSL_DISTRO;
  const shell = "wsl.exe";
  const args = wslDistro ? ["-d", wslDistro, "-e", "bash", "-l"] : ["-e", "bash", "-l"];

  ptyProcess = pty.spawn(shell, args, {
    name: "xterm-256color",
    cols: 120,
    rows: 30,
    cwd: process.env.USERPROFILE || "C:\\",
    env: {
      ...process.env,
      TERM: "xterm-256color"
    }
  });

  ptyProcess.onData((data) => {
    if (mainWindow && !mainWindow.isDestroyed()) {
      mainWindow.webContents.send("terminal:data", data);
    }
  });

  ptyProcess.onExit(() => {
    if (mainWindow && !mainWindow.isDestroyed()) {
      mainWindow.webContents.send("terminal:data", "\r\n[WSL exited]\r\n");
    }
  });
}

ipcMain.on("terminal:write", (_event, data) => {
  if (ptyProcess) {
    ptyProcess.write(data);
  }
});

ipcMain.on("terminal:resize", (_event, size) => {
  if (ptyProcess && size && size.cols && size.rows) {
    ptyProcess.resize(size.cols, size.rows);
  }
});

ipcMain.on("health:check", (event) => {
  const token = process.env.GITHUB_TOKEN || "";
  const repoPath = process.env.REPO_PATH || app.getAppPath();
  const repoWsl = toWslPath(repoPath);
  const checks = [];

  checks.push(`GITHUB_TOKEN: ${token ? "OK" : "MISSING"}`);
  checks.push(`REPO_PATH: ${repoPath}`);
  checks.push(`REPO_WSL: ${repoWsl || "INVALID"}`);

  const scriptPath = ensureImproveScript();
  checks.push(`improve.sh: ${existsSync(scriptPath) ? "OK" : "MISSING"}`);

  const cmd = [
    "command -v gh >/dev/null 2>&1 && echo 'gh: OK' || echo 'gh: MISSING'",
    "command -v codex >/dev/null 2>&1 && echo 'codex: OK' || echo 'codex: MISSING'",
    "wsl.exe -l -q | head -n 1 >/dev/null 2>&1 && echo 'WSL: OK' || echo 'WSL: MISSING'"
  ].join(" ; ");

  try {
    const child = spawn("wsl.exe", ["-e", "bash", "-lc", cmd], { env: process.env });
    let out = "";
    child.stdout.on("data", (d) => (out += d.toString()));
    child.stderr.on("data", (d) => (out += d.toString()));
    child.on("close", () => {
      const result = `${checks.join("\n")}\n${out.trim()}`;
      event.sender.send("health:result", result);
    });
  } catch (err) {
    event.sender.send("health:result", `${checks.join("\n")}\nWSL: ERROR ${err.message}`);
  }
});

ipcMain.on("improve:start", (event, payload) => {
  const iterations = Number(payload?.iterations || 5);
  const repoWinPath = process.env.REPO_PATH || app.getAppPath();
  let repoWslPath = toWslPath(repoWinPath);
  if (!repoWslPath) {
    const fallbackWin = "C:\\codex-ai-exe";
    repoWslPath = toWslPath(fallbackWin);
  }
  const scriptPath = ensureImproveScript();

  if (!repoWslPath) {
    event.sender.send("improve:done", "Missing REPO_PATH. Set REPO_PATH to a Windows path like C:\\\\codex-ai-exe.");
    return;
  }

  const token = process.env.GITHUB_TOKEN || "";
  if (!token) {
    event.sender.send("improve:done", "Missing GITHUB_TOKEN env var.");
    return;
  }

  const cmd = [
    `export REPO_PATH=${escapeShell(repoWslPath)}`,
    `export GITHUB_REPO=${escapeShell("mordechimenaker-create/codex-ai-exe")}`,
    `export GITHUB_TOKEN=${escapeShell(token)}`,
    `export MAX_ITERATIONS=${iterations}`,
    "export AUTO_MERGE=1",
    `bash ${escapeShell(toWslPath(scriptPath))}`
  ].join(" ; ");

  const env = {
    ...process.env,
    GITHUB_TOKEN: token,
    REPO_PATH: repoWinPath,
    GITHUB_REPO: "mordechimenaker-create/codex-ai-exe",
    WSLENV: appendWslenv(process.env.WSLENV, "GITHUB_TOKEN/p:REPO_PATH/p:GITHUB_REPO/p")
  };
  const child = spawn("wsl.exe", ["-e", "bash", "-lc", cmd], { env });

  child.stdout.on("data", (data) => {
    event.sender.send("improve:log", data.toString());
  });

  child.stderr.on("data", (data) => {
    event.sender.send("improve:log", data.toString());
  });

  child.on("close", (code) => {
    event.sender.send("improve:done", `Improve loop finished with code ${code}`);
  });
});

ipcMain.on("ai:prompt", (event, payload) => {
  const prompt = (payload && payload.prompt) || "";
  const id = (payload && payload.id) || "";
  if (!prompt.trim()) {
    event.sender.send("ai:done", { id, error: "Prompt is empty" });
    return;
  }

  const history = (payload && payload.history) || "";
  streamCodex(prompt, history, (chunk) => {
    event.sender.send("ai:chunk", { id, chunk });
  }).then(
    (text) => event.sender.send("ai:done", { id, text }),
    (error) => event.sender.send("ai:done", { id, error })
  );
});

function bashEscape(value) {
  const str = String(value);
  return `'${str.replace(/'/g, `'\"'\"'`)}'`;
}

function buildCodexCommand(prompt, history) {
  const install = "command -v codex >/dev/null 2>&1 || npm install -g @openai/codex";
  const systemHint = [
    "You are a terminal command generator.",
    "Return ONLY the command(s) to run, no explanations.",
    "If admin is needed, include sudo.",
    "If you are unsure, still return the safest command you can.",
    "Do not use code fences."
  ].join(" ");
  const historyBlock = history ? `Conversation so far:\n${history}\n` : "";
  const combined = bashEscape(`${systemHint}\n${historyBlock}User request: ${prompt}`);
  const exec = `codex exec --skip-git-repo-check ${combined}`;
  return `${install} && ${exec}`;
}

function toWslPath(winPath) {
  if (!winPath) {
    return "";
  }
  const normalized = winPath.replace(/\//g, "\\");
  if (normalized.startsWith("\\\\")) {
    return "";
  }
  const match = normalized.match(/^([A-Za-z]):\\(.*)$/);
  if (!match) {
    return "";
  }
  const drive = match[1].toLowerCase();
  const rest = match[2].replace(/\\/g, "/");
  return `/mnt/${drive}/${rest}`;
}

function escapeShell(value) {
  return `'${String(value).replace(/'/g, `'\"'\"'`)}'`;
}

function appendWslenv(current, entry) {
  if (!current) {
    return entry;
  }
  const parts = current.split(":");
  if (parts.includes(entry)) {
    return current;
  }
  return `${current}:${entry}`;
}

function ensureImproveScript() {
  const userDataDir = app.getPath("userData");
  const target = path.join(userDataDir, "improve.sh");
  try {
    if (!fs.existsSync(target)) {
      fs.writeFileSync(target, IMPROVE_SCRIPT_CONTENT, { encoding: "utf8", mode: 0o755 });
    }
    return target;
  } catch (_err) {
    // Fallback to app path in dev.
    return path.join(app.getAppPath(), "scripts", "improve.sh");
  }
}

function streamCodex(prompt, history, onChunk) {
  return new Promise((resolve, reject) => {
    if (process.platform !== "win32") {
      reject("Codex CLI via WSL is supported on Windows only.");
      return;
    }

    const wslDistro = process.env.WSL_DISTRO;
    const cmd = buildCodexCommand(prompt, history);
    const args = wslDistro
      ? ["-d", wslDistro, "-e", "bash", "-lc", cmd]
      : ["-e", "bash", "-lc", cmd];

    const child = spawn("wsl.exe", args, {
      env: process.env
    });

    let stdout = "";
    let stderr = "";

    child.stdout.on("data", (data) => {
      const chunk = data.toString();
      stdout += chunk;
      if (onChunk) {
        onChunk(chunk);
      }
    });

    child.stderr.on("data", (data) => {
      stderr += data.toString();
    });

    child.on("error", (err) => {
      reject(`WSL error: ${err.message}`);
    });

    child.on("close", (code) => {
      const output = stdout.trim();
      const errorOut = stderr.trim();
      if (code !== 0 && !output) {
        reject(errorOut || `codex exec exited with code ${code}`);
        return;
      }
      resolve(output || errorOut || "(no output)");
    });
  });
}

function warnIfUnc() {
  const appPath = app.getAppPath();
  if (!mainWindow || mainWindow.isDestroyed()) {
    return;
  }
  if (appPath.startsWith("\\\\") || appPath.includes("\\\\wsl$\\")) {
    mainWindow.webContents.send(
      "app:warning",
      "App is running from a UNC/WSL path. For stability, run from C:\\\\codex-ai-exe."
    );
  }
}

function sendWslStatus() {
  if (!mainWindow || mainWindow.isDestroyed()) {
    return;
  }
  let status = "WSL: Unknown";
  try {
    const distro = process.env.WSL_DISTRO;
    status = distro ? `WSL: ${distro}` : "WSL: Available";
  } catch (_err) {
    status = "WSL: Unknown";
  }
  mainWindow.webContents.send("app:warning", status);
  mainWindow.webContents.send("app:status", status);
}

function setupAutoUpdates() {
  autoUpdater.autoDownload = true;
  autoUpdater.on("checking-for-update", () => {
    mainWindow?.webContents.send("app:warning", "Checking for updates...");
  });
  autoUpdater.on("update-available", () => {
    mainWindow?.webContents.send("app:warning", "Update available. Downloading...");
  });
  autoUpdater.on("update-not-available", () => {
    mainWindow?.webContents.send("app:warning", "No updates available.");
  });
  autoUpdater.on("error", (err) => {
    mainWindow?.webContents.send("app:warning", `Update error: ${err?.message || err}`);
  });
  autoUpdater.on("update-downloaded", () => {
    mainWindow?.webContents.send("app:warning", "Update downloaded. Restarting...");
    autoUpdater.quitAndInstall();
  });
}

app.whenReady().then(() => {
  createWindow();
  startPty();
  warnIfUnc();
  sendWslStatus();
  setupAutoUpdates();
  autoUpdater.checkForUpdatesAndNotify();

  app.on("activate", () => {
    if (BrowserWindow.getAllWindows().length === 0) {
      createWindow();
      startPty();
    }
  });
});

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});
